### ISSUE TITLE
PermissionError:[Errno 13] Permission denied: '/genconf/config.yaml'

### ISSUE THREAD

**Issue by Sun-zhe** [mesosphere/open-docs#191]
Hi, 
I got a Mesosphere-EE, and when installed, I got a problelm:
Environment: Fedora 23 server (kernel 4.4), get UI though vnc.
Install cmd:
`$bash dcos_generate_config.ee.sh --web –v
`
```
Running mesosphere/dcos-genconf docker with BUILD_DIR set to /home/mesos-ee/genconf
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
07:53:46:: Logger set to DEBUG
07:53:46:: ====> Starting DCOS installer in web mode
07:53:46:: DCOS Installer v1
07:53:46:: Starting server ('0.0.0.0', 9000)
```
Then I start firefox though vnc, the vnc is on root. then:
```
07:53:57:: Root page requested.
07:53:57:: Serving /usr/local/lib/python3.4/site-packages/dcos_installer/templates/index.html
07:53:58:: Request for configuration type made.
07:53:58:: Configuration file not found, /genconf/config.yaml. Writing new one with all defaults.
07:53:58:: Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "/usr/local/lib/python3.4/site-packages/aiohttp/web.py", line 87, in handle_request
    resp = yield from handler(request)
  File "/usr/local/lib/python3.4/asyncio/coroutines.py", line 206, in coro
    res = func(*args, **kw)
  File "/usr/local/lib/python3.4/site-packages/dcos_installer/async_server.py", line 100, in configure_type
    return web.json_response(backend.determine_config_type())
  File "/usr/local/lib/python3.4/site-packages/dcos_installer/backend.py", line 141, in determine_config_type
    config = get_config(config_path=config_path)
  File "/usr/local/lib/python3.4/site-packages/dcos_installer/backend.py", line 114, in get_config
    return DCOSConfig(config_path=config_path)
  File "/usr/local/lib/python3.4/site-packages/dcos_installer/config/__init__.py", line 66, in __init__
    self.build()
  File "/usr/local/lib/python3.4/site-packages/dcos_installer/config/__init__.py", line 93, in build
    user_config = self.get_config()
  File "/usr/local/lib/python3.4/site-packages/dcos_installer/config/__init__.py", line 145, in get_config
    self.write()
  File "/usr/local/lib/python3.4/site-packages/dcos_installer/config/__init__.py", line 155, in write
    data = open(self.config_path, 'w')
PermissionError: [Errno 13] Permission denied: '/genconf/config.yaml'
```
But I already have a genconf/config.yaml, it look like:
```
bootstrap_url: http://<bootstrap_public_ip>:<your_port>
cluster_name: '<cluster-name>'
exhibitor_storage_backend: zookeeper
exhibitor_zk_hosts: <host1>:2181,<host2>:2181,<host3>:2181
exhibitor_zk_path: /dcos
master_discovery: static
master_list:
- <master-private-ip-1>
- <master-private-ip-2>
- <master-private-ip-3>
superuser_username: <username>
superuser_password_hash: <hashed-password>
resolvers:
- 8.8.8.8
- 8.8.4.4
```
I do not know what’s going on. If you have any idear, please let me know, thank you very much!

**Comment by ssk2** [comment]
Hi @Sun-zhe - please raise this issue with the support team directly at support@mesosphere.com. They deal with EE support!

**Comment by Sun-zhe** [comment]
I had send an email to support@mesosphere.com two days ago, but no replay.

**Comment by ssk2** [comment]
@sun-zhe, I'll look into it!
